# Generated by Django 5.2.5 on 2025-08-26 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100, unique=True)),
                ('supplier_col', models.JSONField(blank=True, default=dict)),
                ('supplier_mapp_col', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.CharField(max_length=10)),
                ('supplier', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=10)),
                ('part_description', models.CharField(max_length=100)),
                ('part_number', models.CharField(max_length=100)),
                ('trade_price', models.CharField(max_length=10)),
                ('total_count', models.CharField(max_length=10)),
                ('purchase_count', models.CharField(max_length=10)),
                ('total_price', models.CharField(max_length=10)),
                ('actual_price', models.CharField(max_length=10)),
                ('profit', models.CharField(max_length=10)),
                ('selling_price_exc_gst', models.CharField(max_length=10)),
                ('gst', models.CharField(max_length=10)),
                ('selling_price_inc_gst', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SingleInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.CharField(max_length=10)),
                ('invoice_filepath', models.CharField(max_length=155, unique=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.newsupplier')),
            ],
        ),
    ]
