# Generated by Django 5.2.5 on 2025-08-28 07:17

import mainapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsupplier',
            name='supplier_mapp_col',
            field=models.JSONField(blank=True, default=mainapp.models.default_mapping),
        ),
    ]
