# Generated by Django 5.2.5 on 2025-09-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_newsupplier_supplier_mapp_col'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsupplier',
            name='supplier_col',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
