# Generated by Django 5.2.5 on 2025-09-01 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_newsupplier_supplier_col'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnEditingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lst_array', models.JSONField(blank=True, default=list)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.newsupplier')),
            ],
        ),
    ]
