# Generated by Django 5.2.5 on 2025-09-01 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_columneditingstate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ColumnEditingState',
        ),
    ]
