# Generated by Django 5.2.5 on 2025-09-01 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_delete_columneditingstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnEditingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_state', models.JSONField(blank=True, default=list)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.newsupplier')),
            ],
        ),
    ]
