# Generated by Django 5.2.5 on 2025-09-02 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_columneditingstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseEditingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_state', models.JSONField(blank=True, default=list)),
                ('gst', models.CharField(max_length=10)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.newsupplier')),
            ],
        ),
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit', models.CharField(max_length=10)),
                ('gst', models.CharField(max_length=10)),
                ('min', models.CharField(max_length=10)),
                ('max', models.CharField(max_length=10)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.newsupplier')),
            ],
        ),
    ]
