# Generated by Django 5.2.5 on 2025-09-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_caseeditingstate_cases'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='gst_mapp',
            field=models.CharField(blank=True, default='', max_length=155),
        ),
        migrations.AddField(
            model_name='cases',
            name='profit_mapp',
            field=models.CharField(blank=True, default='', max_length=155),
        ),
    ]
