# Generated by Django 5.2.5 on 2025-09-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_cases_gst_mapp_cases_profit_mapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseeditingstate',
            name='gst_mapp',
            field=models.CharField(blank=True, default='', max_length=155),
        ),
        migrations.AddField(
            model_name='caseeditingstate',
            name='profit_mapp',
            field=models.CharField(blank=True, default='', max_length=155),
        ),
    ]
